version: "3.5"
services:
  main:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certs:/etc/nginx/certs
    networks:
      - internal_network

networks:
  internal_network:
    external:
      name: wulkanowy_network
